name: Emulator - Ubuntu

on:
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - uses: jetli/wasm-pack-action@v0.3.0
      with:
        # Optional version of wasm-pack to install(eg. 'v0.9.1', 'latest')
        version: 'latest'
    
    - name: Build
      run: wasm-pack build
      working-directory: emulator
    
    - name: Run tests
      run: wasm-pack test --headless --chrome --node -- --no-fail-fast
      working-directory: emulator

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - run: npm ci
      working-directory: ui
      
    - run: npm run build --if-present
      working-directory: ui
      
    - run: npm start
      working-directory: ui
